CREATE TABLE [KonturEdi].[XMLOrders] (
    [eDIMessageID]                                     UNIQUEIDENTIFIER NOT NULL,
    [OrderNumber]                                      NVARCHAR (20)    NULL,
    [OrderDate]                                        DATE             NULL,
    [OrderStatus]                                      NVARCHAR (20)    NULL,
    [OrderRevisionNumber]                              INT              NULL,
    [Sender]                                           BIGINT           NULL,
    [Recipient]                                        BIGINT           NULL,
    [DocumentType]                                     NVARCHAR (10)    NULL,
    [CreationDateTime]                                 DATETIME         NULL,
    [CreationDateTimeBySender]                         DATETIME         NULL,
    [ContractIdentificator]                            NVARCHAR (50)    NULL,
    [SellerGLN]                                        NVARCHAR (20)    NULL,
    [SellerOrganizationName]                           NVARCHAR (255)   NULL,
    [SellerOrganizationINN]                            NVARCHAR (20)    NULL,
    [SellerOrganizationKPP]                            NVARCHAR (20)    NULL,
    [SellerRussianAddressRegionISOCode]                NVARCHAR (255)   NULL,
    [SellerRussianAddressCity]                         NVARCHAR (255)   NULL,
    [SellerRussianAddressStreet]                       NVARCHAR (255)   NULL,
    [SellerRussianAddressHouse]                        NVARCHAR (255)   NULL,
    [SellerRussianAddressFlat]                         NVARCHAR (255)   NULL,
    [SellerRussianAddressPostalCode]                   NVARCHAR (255)   NULL,
    [SellerAdditionalInfoIdentificator]                NVARCHAR (255)   NULL,
    [SellerAdditionalInfoNameOfCEO]                    NVARCHAR (255)   NULL,
    [SellerAdditionalInfoNameOfAccountant]             NVARCHAR (255)   NULL,
    [SellerContactInfoCEOName]                         NVARCHAR (255)   NULL,
    [SellerContactInfoAccountantName]                  NVARCHAR (255)   NULL,
    [BuyerGLN]                                         NVARCHAR (20)    NULL,
    [BuyerOrganizationName]                            NVARCHAR (255)   NULL,
    [BuyerOrganizationINN]                             NVARCHAR (20)    NULL,
    [BuyerOrganizationKPP]                             NVARCHAR (20)    NULL,
    [BuyerRussianAddressRegionISOCode]                 NVARCHAR (255)   NULL,
    [BuyerRussianAddressCity]                          NVARCHAR (255)   NULL,
    [BuyerRussianAddressStreet]                        NVARCHAR (255)   NULL,
    [BuyerRussianAddressHouse]                         NVARCHAR (255)   NULL,
    [BuyerRussianAddressFlat]                          NVARCHAR (255)   NULL,
    [BuyerRussianAddressPostalCode]                    NVARCHAR (255)   NULL,
    [BuyerAdditionalInfoPhone]                         NVARCHAR (255)   NULL,
    [BuyerAdditionalInfoOrderContact]                  NVARCHAR (255)   NULL,
    [BuyerContactInfoName]                             NVARCHAR (255)   NULL,
    [BuyerContactInfoPhone]                            NVARCHAR (255)   NULL,
    [BuyerContactInfoEmail]                            NVARCHAR (255)   NULL,
    [DeliveryInfoRequestedDeliveryDateTime]            DATE             NULL,
    [DeliveryInfoShipToGLN]                            NVARCHAR (20)    NULL,
    [DeliveryInfoShipToLocalizationType]               NVARCHAR (20)    NULL,
    [DeliveryInfoShipToOrganizationName]               NVARCHAR (255)   NULL,
    [DeliveryInfoShipToOrganizationINN]                NVARCHAR (20)    NULL,
    [DeliveryInfoShipToOrganizationKPP]                NVARCHAR (20)    NULL,
    [DeliveryInfoShipToRussianAddressRegionISOCode]    NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressCity]             NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressStreet]           NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressHouse]            NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressFlat]             NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressPostalCode]       NVARCHAR (255)   NULL,
    [DeliveryInfoShipToGeoCoordinatesLatitude]         NVARCHAR (255)   NULL,
    [DeliveryInfoShipToGeoCoordinatesLongitude]        NVARCHAR (255)   NULL,
    [DeliveryInfoShipToContactInfoDeliveryContactName] NVARCHAR (255)   NULL,
    [DeliveryInfoTransportationVehicleArrivalDateTime] DATETIME         NULL,
    [Comment]                                          NVARCHAR (255)   NULL,
    [CurrencyISOCode]                                  NVARCHAR (3)     NULL,
    [TotalSumExcludingTaxes]                           NUMERIC (10, 2)  NULL,
    CONSTRAINT [PK_XMLOrders] PRIMARY KEY CLUSTERED ([eDIMessageID] ASC)
);


GO

