CREATE TABLE [KonturEdi].[XMLRecadvs] (
    [eDIMessageID]                                       UNIQUEIDENTIFIER NOT NULL,
    [Sender]                                             BIGINT           NULL,
    [Recipient]                                          BIGINT           NULL,
    [DocumentType]                                       NVARCHAR (10)    NULL,
    [CreationDateTime]                                   DATETIME         NULL,
    [CreationDateTimeBySender]                           DATETIME         NULL,
    [ReceivingAdviceNumber]                              NVARCHAR (50)    NULL,
    [ReceivingAdviceDate]                                DATETIME         NULL,
    [OriginOrderNumber]                                  NVARCHAR (50)    NULL,
    [OriginOrderDate]                                    DATETIME         NULL,
    [ContractIdentificator]                              NVARCHAR (50)    NULL,
    [DespatchIdentificatorNumber]                        NVARCHAR (50)    NULL,
    [DespatchIdentificatorDate]                          DATETIME         NULL,
    [SellerGLN]                                          NVARCHAR (20)    NULL,
    [SellerOrganizationName]                             NVARCHAR (255)   NULL,
    [SellerOrganizationINN]                              NVARCHAR (20)    NULL,
    [SellerOrganizationKPP]                              NVARCHAR (20)    NULL,
    [SellerRussianAddressRegionISOCode]                  NVARCHAR (255)   NULL,
    [SellerRussianAddressCity]                           NVARCHAR (255)   NULL,
    [SellerRussianAddressStreet]                         NVARCHAR (255)   NULL,
    [SellerRussianAddressHouse]                          NVARCHAR (255)   NULL,
    [SellerRussianAddressFlat]                           NVARCHAR (255)   NULL,
    [SellerRussianAddressPostalCode]                     NVARCHAR (255)   NULL,
    [SellerAdditionalInfoIdentificator]                  NVARCHAR (255)   NULL,
    [SellerAdditionalInfoNameOfCEO]                      NVARCHAR (255)   NULL,
    [SellerAdditionalInfoNameOfAccountant]               NVARCHAR (255)   NULL,
    [SellerContactInfoCEOName]                           NVARCHAR (255)   NULL,
    [SellerContactInfoAccountantName]                    NVARCHAR (255)   NULL,
    [BuyerGLN]                                           NVARCHAR (20)    NULL,
    [BuyerOrganizationName]                              NVARCHAR (255)   NULL,
    [BuyerOrganizationINN]                               NVARCHAR (20)    NULL,
    [BuyerOrganizationKPP]                               NVARCHAR (20)    NULL,
    [BuyerRussianAddressRegionISOCode]                   NVARCHAR (255)   NULL,
    [BuyerRussianAddressCity]                            NVARCHAR (255)   NULL,
    [BuyerRussianAddressStreet]                          NVARCHAR (255)   NULL,
    [BuyerRussianAddressHouse]                           NVARCHAR (255)   NULL,
    [BuyerRussianAddressFlat]                            NVARCHAR (255)   NULL,
    [BuyerRussianAddressPostalCode]                      NVARCHAR (255)   NULL,
    [BuyerAdditionalInfoPhone]                           NVARCHAR (255)   NULL,
    [BuyerAdditionalInfoOrderContact]                    NVARCHAR (255)   NULL,
    [BuyerContactInfoName]                               NVARCHAR (255)   NULL,
    [BuyerContactInfoPhone]                              NVARCHAR (255)   NULL,
    [BuyerContactInfoEmail]                              NVARCHAR (255)   NULL,
    [InvoiceeGLN]                                        NVARCHAR (255)   NULL,
    [InvoiceeOrganizationName]                           NVARCHAR (255)   NULL,
    [InvoiceeOrganizationINN]                            NVARCHAR (255)   NULL,
    [InvoiceeOrganizationKPP]                            NVARCHAR (255)   NULL,
    [InvoiceeRussianAddressRegionISOCode]                NVARCHAR (255)   NULL,
    [InvoiceeRussianAddressCity]                         NVARCHAR (255)   NULL,
    [InvoiceeRussianAddressStreet]                       NVARCHAR (255)   NULL,
    [InvoiceeRussianAddressHouse]                        NVARCHAR (255)   NULL,
    [InvoiceeRussianAddressPostalCode]                   NVARCHAR (255)   NULL,
    [DeliveryInfoRequestedDeliveryDateTime]              DATE             NULL,
    [DeliveryInfoWaybillNumber]                          NVARCHAR (255)   NULL,
    [DeliveryInfoWaybillDate]                            DATE             NULL,
    [DeliveryInfoShipFromGLN]                            NVARCHAR (20)    NULL,
    [DeliveryInfoShipFromLocalizationType]               NVARCHAR (20)    NULL,
    [DeliveryInfoShipFromOrganizationName]               NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromOrganizationINN]                NVARCHAR (20)    NULL,
    [DeliveryInfoShipFromOrganizationKPP]                NVARCHAR (20)    NULL,
    [DeliveryInfoShipFromRussianAddressRegionISOCode]    NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromRussianAddressCity]             NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromRussianAddressStreet]           NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromRussianAddressHouse]            NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromRussianAddressFlat]             NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromRussianAddressPostalCode]       NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromGeoCoordinatesLatitude]         NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromGeoCoordinatesLongitude]        NVARCHAR (255)   NULL,
    [DeliveryInfoShipFromContactInfoDeliveryContactName] NVARCHAR (255)   NULL,
    [DeliveryInfoShipToGLN]                              NVARCHAR (20)    NULL,
    [DeliveryInfoShipToLocalizationType]                 NVARCHAR (20)    NULL,
    [DeliveryInfoShipToOrganizationName]                 NVARCHAR (255)   NULL,
    [DeliveryInfoShipToOrganizationINN]                  NVARCHAR (20)    NULL,
    [DeliveryInfoShipToOrganizationKPP]                  NVARCHAR (20)    NULL,
    [DeliveryInfoShipToRussianAddressRegionISOCode]      NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressCity]               NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressStreet]             NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressHouse]              NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressFlat]               NVARCHAR (255)   NULL,
    [DeliveryInfoShipToRussianAddressPostalCode]         NVARCHAR (255)   NULL,
    [DeliveryInfoShipToGeoCoordinatesLatitude]           NVARCHAR (255)   NULL,
    [DeliveryInfoShipToGeoCoordinatesLongitude]          NVARCHAR (255)   NULL,
    [DeliveryInfoShipToContactInfoDeliveryContactName]   NVARCHAR (255)   NULL,
    [DeliveryInfoTransportationVehicleArrivalDateTime]   DATETIME         NULL,
    [Comment]                                            NVARCHAR (255)   NULL,
    [CurrencyISOCode]                                    NVARCHAR (3)     NULL,
    [TotalSumExcludingTaxes]                             NUMERIC (10, 2)  NULL,
    CONSTRAINT [PK_XMLRecadvs] PRIMARY KEY CLUSTERED ([eDIMessageID] ASC)
);


GO

